name: Build Wiki
on:
  push:
    branches:
      - patch-2
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@patch-2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@patch-2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: stellarity.brokenemp.xyz
          CONFIG_FILE: mkdocs.yml
          REQUIREMENTS: requirements.txt
