name: Build Datapack
on:
  push:
    branches:
      - master
    paths:
      - 'data/**'
      - 'overlay_1_20_2/**',
      - 'pack.mcmeta'
      - 'pack.png'
      - 'LICENSE.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/upload-artifact@v4
      with:
        name: Stellarity-DP-DEV
        path: |
          data/
          overlay_1_20_2/
          pack.mcmeta
          pack.png
          LICENSE.md
        retention-days: 7
        compression-level: 9
